### ISSUE TITLE
Update font of markdown

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/data_threefold#50]
Received feedback from Kristof that current font is not good.

<img width="1098" alt="Screenshot 2021-07-08 at 09 14 32" src="https://user-images.githubusercontent.com/20182572/124871800-2a8b6400-dfcd-11eb-88c0-0d42021944bd.png">

Let's try applying Harmonia https://fonts.google.com/?query=harmonia
or smth else but aiming to get as close to this:

<img width="839" alt="Screenshot 2021-07-08 at 09 45 50" src="https://user-images.githubusercontent.com/20182572/124875259-590b3e00-dfd1-11eb-9a71-a540c0f7c63f.png">

and see if it works.

**Comment by ehab-hassan** [comment]
![photo_٢٠٢١-٠٧-٠٨_١٣-٢٨-٠٣](https://user-images.githubusercontent.com/10484295/124916509-0d698c00-dff3-11eb-91cb-75b56b9e56e8.jpg)
we made font smaller and a bit wider and not bold 
not pushed yet at development if ok I ll push

**Comment by ehab-hassan** [comment]
@Vilnite font updated at io, if it Ok we can go through all websites with blog and news and update all
